import type { Metadata } from "next";
import NoiseOverlay from "@/components/Background/NoiseOverlay";
import Navigation from "@/components/Navigation";
import SplashScreen from "@/components/SplashScreen";
import Footer from "@/components/Footer";

import "@/app/globals.css";
import "@/app/fonts.css";

export const metadata: Metadata = {
  title: "Fadil Hisyam | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="root">
        <SplashScreen />
        <Navigation />
        {children}
        <Footer />
        {/* <Animate /> */}
        <NoiseOverlay />
      </body>
    </html>
  );
}
